name: Test

on:
  pull_request:
    branches: [ master ]
  push:
    branches:
      - '*'
    paths-ignore:
      - 'README.md'
      - 'LICENSE.txt'
      - 'dist/*'
      - '.gitignore'
      - '.github/workflows/package.yml'

jobs:
  test:
    name: Run automated tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Test
      run: |
        npm ci
        npm test
